//============================================================================
// Name        : VtkHeaders.h
// Created on  : 23.11.2021
// Author      : Tokmakov Andrey
// Version     : 1.0
// Copyright   : Your copyright notice
// Description : Points
//============================================================================

#ifndef CPPPROJECTS_VTKHEADERS_H
#define CPPPROJECTS_VTKHEADERS_H

#include <vtkDistancePolyDataFilter.h>
#include <vtkParametricSuperEllipsoid.h>
#include <vtkParametricSuperToroid.h>
#include <vtkScalarBarActor.h>
#include <vtkMatrix3x3.h>
#include <vtkSmoothPolyDataFilter.h>
#include <vtkHexagonalPrism.h>
#include <vtkQuadricDecimation.h>
#include <vtkHexahedron.h>
#include <vtkUnstructuredGrid.h>
#include <vtkMergePoints.h>
#include <vtkMarchingCubes.h>
#include <vtkExtractEdges.h>
#include <vtkDataSetSurfaceFilter.h>
#include <vtkCenterOfMass.h>
#include <vtkBoundingBox.h>
#include <vtkPentagonalPrism.h>
#include <vtkSliderRepresentation2D.h>
#include <vtkProperty2D.h>
#include <vtkOBBTree.h>
#include <vtkSliderWidget.h>
#include <vtkSliderRepresentation.h>
#include <vtkLineSource.h>
#include <vtkVectorText.h>
#include <vtkFollower.h>
#include <vtkTextActor3D.h>
#include <vtkInteractorStyleSwitch.h>
#include <vtkClipPolyData.h>
#include <vtkVariantArray.h>
#include <vtkBandedPolyDataContourFilter.h>
#include <vtkCurvatures.h>
#include <vtkIdFilter.h>
#include <vtkArrowSource.h>
#include <vtkFeatureEdges.h>
#include <vtkElevationFilter.h>
#include <vtkReverseSense.h>
#include <vtkMaskPoints.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkTriangleFilter.h>
#include <vtkCleanPolyData.h>
#include <vtkSuperquadricSource.h>
#include <vtkParametricTorus.h>
#include <vtkParametricRandomHills.h>
#include <vtkParametricFunctionSource.h>
#include <vtkColorSeries.h>
#include <vtkPlaneSource.h>
#include <vtkIntersectionPolyDataFilter.h>
#include <vtkBooleanOperationPolyDataFilter.h>
#include <vtkTextProperty.h>
#include <vtkCollisionDetectionFilter.h>
#include <vtkTextActor.h>
#include <vtkPointSource.h>
#include <vtkCellArrayIterator.h>
#include <vtkStripper.h>
#include <vtkDelaunay3D.h>
#include <vtkAppendFilter.h>
#include <vtkCommand.h>
#include <vtkTransform.h>
#include <vtkActor.h>
#include <vtkCamera.h>
#include <vtkOBJWriter.h>
#include <vtkCellCenters.h>
#include <vtkGlyph3DMapper.h>
#include <vtkNamedColors.h>
#include <vtkNew.h>
#include <vtkPolyDataMapper.h>
#include <vtkProperty.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkInteractorStyleTrackballCamera.h>
#include <vtkRenderer.h>
#include <vtkSmartPointer.h>
#include <vtkCellData.h>
#include <vtkConnectivityFilter.h>
#include <vtkConeSource.h>
#include <vtkCubeSource.h>
#include <vtkBYUReader.h>
#include <vtkOBJReader.h>
#include <vtkPLYReader.h>
#include <vtkPolyDataReader.h>
#include <vtkSTLReader.h>
#include <vtkSphereSource.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkOutlineFilter.h>
#include <vtkGenericCell.h>
#include <vtkBoxWidget.h>
#include <vtkColor.h>
#include <vtkCellIterator.h>
#include <vtkColorTransferFunction.h>
#include <vtkFixedPointVolumeRayCastMapper.h>
#include <vtkMetaImageReader.h>
#include <vtkPiecewiseFunction.h>
#include <vtkVolume.h>
#include <vtkVolumeProperty.h>
#include <vtkPolyDataConnectivityFilter.h>
#include <vtkAppendPolyData.h>
#include <vtkLookupTable.h>
#include <vtkMultiBlockDataSet.h>
#include <vtkMultiBlockPLOT3DReader.h>
#include <vtkPolyDataNormals.h>
#include <vtkStructuredGrid.h>
#include <vtkStructuredGridGeometryFilter.h>
#include <vtkStructuredGridOutlineFilter.h>
#include <vtkWarpVector.h>
#include <vtkFillHolesFilter.h>
#include <vtkCellArray.h>
#include <vtkCellLocator.h>
#include <vtkDataSetMapper.h>
#include <vtkDelaunay2D.h>
#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkImageData.h>
#include <vtkLine.h>
#include <vtkMinimalStandardRandomSequence.h>
#include <vtkPointData.h>
#include <vtkPoints.h>
#include <vtkPolyData.h>
#include <vtkSTLWriter.h>
#include <vtkTriangle.h>
#include <vtkVertexGlyphFilter.h>
#include <vtkWarpScalar.h>
#include <vtkProbeFilter.h>
#include <vtkXMLPolyDataWriter.h>
#include <vtkSphere.h>
#include <vtkCutter.h>
#include <vtkMath.h>
#include <vtkPlane.h>
#include <vtkContourFilter.h>
#include <vtkImplicitBoolean.h>
#include <vtkSampleFunction.h>
#include <vtkCylinderSource.h>

#endif //CPPPROJECTS_VTKHEADERS_H
